# syntax=docker/dockerfile:1

FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
COPY prisma.config.ts ./
COPY prisma ./prisma
ENV DATABASE_URL=postgresql://build:build@localhost:5432/build
RUN npm install

COPY . .

EXPOSE 7878

CMD ["sh", "docker/entrypoint.dev.sh"]
